//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public Nullable<int> IdDocument { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public Nullable<int> RecipientAddressId { get; set; }
        public Nullable<bool> Status { get; set; }
        public int UserCreate { get; set; }
        public System.DateTime DatetimeCreate { get; set; }
        public Nullable<int> UserUpdate { get; set; }
        public Nullable<System.DateTime> DatetimeUpdate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> UserDelete { get; set; }
        public Nullable<System.DateTime> DatetimeDelete { get; set; }
        public string GuiId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string UserAuthorization { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Document Document { get; set; }
    }
}
